Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  BaseDomain:
    Type: String
    Description: Base Domain name

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Environment}-lambda-function"
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${AppName}-${Environment}-lambda-function-execution-role"
      Environment:
        Variables:
          APP_NAME: !Ref AppName
          ENVIRONMENT: !Ref Environment
          REGION: !Ref AWS::Region
          BASE_DOMAIN: !Ref BaseDomain
      Timeout: 300
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "bootstrap"}
      Layers:
        - !Sub '{{resolve:ssm:/${AppName}/${Environment}/lambda/layer}}'

Outputs:
  LambdaFunctionArn:
    Description: "Ledger lambda function arn"
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub "${AppName}-${Environment}-lambda-function-arn"