Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  BaseDomain:
    Type: String
    Description: Base Domain name

  LambdaBucket:
    Type: String
    Description: S3 bucket name used by lambda

  LambdaArtifactKey:
    Type: String
    Description: S3 bucket key used by lambda function zip

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Environment}-lambda-function"
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${AppName}-${Environment}-lambda-function-execution-role"
      Environment:
        Variables:
          APP_NAME: !Ref AppName
          ENVIRONMENT: !Ref Environment
          REGION: !Ref AWS::Region
          BASE_DOMAIN: !Ref BaseDomain
      Timeout: 300
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: !Ref LambdaArtifactKey
      Layers:
        - !Sub '{{resolve:ssm:/${AppName}/${Environment}/lambda/layer}}'

  ApiGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${AppName}-${Environment}-api-gateway-arn"
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LedgerLambdaArn}/invocations
          - LedgerLambdaArn: !GetAtt LambdaFunction.Arn
      PayloadFormatVersion: "2.0"

  ApiGatewayRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${AppName}-${Environment}-api-gateway-arn"
      RouteKey: "ANY /{proxy+}"
      Target: !Sub "integrations/${ApiGatewayIntegration}"


  ApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: 
        !Sub
          - "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*"
          - ApiGateway:
              Fn::ImportValue: !Sub "${AppName}-${Environment}-api-gateway-arn"
