Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  LambdaBucket:
    Type: String
    Description: S3 bucket name used by lambda

Resources:
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub "${AppName}-${Environment}-lambda-layer"
      CompatibleRuntimes:
        - python3.12
      Content:
        S3Bucket: !Ref LambdaBucket
        S3Key: "bootstrap/layer.zip"

  LambdaLayerParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/lambda/layer"
      Type: String
      Value: !GetAtt LambdaLayer.LayerVersionArn