version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip

  build:
    commands:
      - echo "=== Packaging Lambda Function ==="
      - cd infrastructure/assets/db-init/lambda
      - zip db-init-function.zip handler.py
      - cd -

      - echo "=== Building Lambda Layer ==="
      - mkdir -p layer_build/python/lib/python3.11/site-packages
      - pip install -r infrastructure/assets/db-init/lambda/requirements.txt -t layer_build/python/lib/python3.11/site-packages
      - cd layer_build
      - zip -r ../db-init-layer.zip python
      - cd -

  post_build:
    commands:
      - echo "=== Uploading Artifacts ==="
      - aws s3 cp infrastructure/assets/db-init/lambda/db-init-function.zip s3://$ASSET_BUCKET/db-init/lambda/db-init-function.zip

      - aws s3 cp db-init-layer.zip s3://$ASSET_BUCKET/db-init/lambda/db-init-layer.zip

      - aws s3 cp infrastructure/assets/db-init/sql/init.sql s3://$ASSET_BUCKET/db-init/sql/init.sql

artifacts:
  files:
    - infrastructure/assets/db-init/lambda/db-init-function.zip
    - db-init-layer.zip
