AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for Lambda Pipeline

Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger

  Environment:
    Type: String
    Description: Environment name

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN
    NoEcho: True

  LambdaBucket:
    Type: String
    Description: S3 bucket name used by lambda

Resources:
  ### IAM Role for CodePipeline
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-${Environment}-lambda-pipeline-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole

  CodePipelinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AppName}-${Environment}-lambda-pipeline-policy
      Roles:
        - !Ref CodePipelineRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowS3BucketAccess
            Effect: Allow
            Action:
              - s3:GetBucketVersioning
              - s3:GetBucketAcl
              - s3:GetBucketLocation
            Resource: !Sub "arn:aws:s3:::${LambdaBucket}"

          - Sid: AllowS3ObjectAccess
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: !Sub "arn:aws:s3:::${LambdaBucket}/*"

          - Effect: Allow
            Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
            Resource: !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${AppName}-${Environment}-*-build-project"

          - Effect: Allow
            Action:
              - codestar-connections:UseConnection
              - codestar-connections:GetConnectionToken
              - codeconnections:UseConnection
              - codeconnections:GetConnectionToken
            Resource:
              - !Ref GithubConnectionArn

          # Cloudformation
          - Effect: "Allow"
            Action:
              - cloudformation:CreateStack
              - cloudformation:UpdateStack
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackEvents
              - cloudformation:CreateChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:DeleteChangeSet
            "Resource": "*"

          - Effect: Allow
            Action: iam:PassRole
            Resource:
              Fn::ImportValue:
                !Sub "${AppName}-${Environment}-cfn-function-execution-role-name"

Outputs:
  PipelineRoleArn:
    Description: "Pipeline Role Arn"
    Value: !GetAtt CodePipelineRole.Arn
    Export:
      Name: !Sub "${AppName}-${Environment}-lambda-pipeline-role-arn"