Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger

  Environment:
    Type: String
    Description: Environment name
    Default: dev

Resources:
  TriggerFunctionPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-${Environment}-layer-pipeline-trigger-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StartFunctionPipeline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codepipeline:StartPipelineExecution
                Resource: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${AppName}-${Environment}-function-pipeline"

  LayerSuccessRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${AppName}-${Environment}-layer-pipeline-success-trigger"
      EventPattern:
        source:
          - aws.codepipeline
        detail-type:
          - CodePipeline Pipeline Execution State Change
        detail:
          pipeline:
            - !Sub "${AppName}-${Environment}-layer-pipeline"
          state:
            - SUCCEEDED
      Targets:
        - Arn: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${AppName}-${Environment}-function-pipeline"
          Id: "FunctionPipelineTarget"
          RoleArn: !GetAtt TriggerFunctionPipelineRole.Arn