Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  LambdaBucket:
    Type: String
    Description: S3 bucket name used by lambda

  LambdaArtifactKey:
    Type: String
    Description: S3 bucket key used by lambda function zip

  BuildPurpose:
    Type: String
    Description: logical purpose of produced artifact

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Environment}-lambda-${BuildPurpose}"
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role:
        Fn::ImportValue:
          Fn::Sub: "${AppName}-${Environment}-lambda-function-execution-role-name"
      Timeout: 300
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: !Ref LambdaArtifactKey
      Layers:
        - !Sub '{{resolve:ssm:/${AppName}/${Environment}/lambda/layer}}'

Outputs:
  LambdaFunctionName:
    Description: "Ledger lambda function name"
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub "${AppName}-${Environment}-lambda-function-name"
  LambdaFunctionArn:
    Description: "Ledger lambda function arn"
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub "${AppName}-${Environment}-lambda-function-arn"