AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for Lambda Pipeline

Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger

  Environment:
    Type: String
    Description: Environment name
    Default: dev

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN
    Default: arn:aws:codeconnections:eu-north-1:253712034003:connection/2c02ecd9-b115-4cec-967f-a0e4445ecfaa
    NoEcho: True

  SourceRepo:
    Type: String
    Description: owner/repo biçiminde GitHub repo ID'si
    Default: zbalci/ledger-app-aws-serverless

  SourceRepoURL:
    Type: String
    Description: owner/repo biçiminde GitHub repo URL
    Default: https://github.com/zbalci/ledger-app-aws-serverless

  SourceBranch:
    Type: String
    Default: main
    
  BuildPurpose:
    Type: String
    Description: logical purpose of produced artifact
    Default: lambda

  LambdaBucket:
    Type: String
    Description: S3 bucket name used by lambda
    Default: ledger-app-aws-lambda

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-${Environment}-${BuildPurpose}-build-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      Policies:
        - PolicyName: AdditionalPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${LambdaBucket}/*"

              - Sid: GitHubConnectionAccess
                Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                  - codestar-connections:GetConnectionToken
                  - codeconnections:UseConnection
                  - codeconnections:GetConnectionToken

                Resource: "*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AppName}-${Environment}-${BuildPurpose}-build-project"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_REGION
            Value: !Ref AWS::Region
            Type: PLAINTEXT
          - Name: ACCOUNT_ID
            Value: !Ref AWS::AccountId
            Type: PLAINTEXT
          - Name: APP_NAME
            Value: !Ref AppName
            Type: PLAINTEXT
          - Name: ENVIRONMENT
            Value: !Ref Environment
      Artifacts:
        Type: S3
        Location: !Ref LambdaBucket 
      Source:
        Auth: 
          Type: CODECONNECTIONS
          Resource: !Ref GithubConnectionArn
        Type: GITHUB
        Location: !Ref SourceRepoURL
        BuildSpec: infrastructure/cicd/lambda/buildspec.yml
        GitCloneDepth: 0   # Full Clone
      TimeoutInMinutes: 5
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/main$
            - Type: FILE_PATH
              Pattern: ^src/web/.*
  #     Artifacts:
  #       Type: CODEPIPELINE 
  #     Source:
  #       Type: CODEPIPELINE
  #       BuildSpec: infrastructure/cicd/lambda/buildspec.yml
  #       GitCloneDepth: 0   # Full Clone
  #     TimeoutInMinutes: 5

  # ### IAM Role for CodePipeline
  # CodePipelineRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: !Sub ${AppName}-${Environment}-${BuildPurpose}-pipeline-role
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: codepipeline.amazonaws.com
  #           Action: sts:AssumeRole

  # CodePipelinePolicy:
  #   Type: AWS::IAM::Policy
  #   Properties:
  #     PolicyName: !Sub ${AppName}-${Environment}-${BuildPurpose}-pipeline-policy
  #     Roles:
  #       - !Ref CodePipelineRole
  #     PolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Sid: AllowS3BucketAccess
  #           Effect: Allow
  #           Action:
  #             - s3:GetBucketVersioning
  #             - s3:GetBucketAcl
  #             - s3:GetBucketLocation
  #           Resource: !Sub "arn:aws:s3:::${LambdaBucket}/*"

  #         - Sid: AllowS3ObjectAccess
  #           Effect: Allow
  #           Action:
  #             - s3:PutObject
  #             - s3:PutObjectAcl
  #             - s3:GetObject
  #             - s3:GetObjectVersion
  #           Resource: !Sub "arn:aws:s3:::${LambdaBucket}/*"

  #         - Effect: Allow
  #           Action:
  #             - codebuild:BatchGetBuilds
  #             - codebuild:StartBuild
  #           Resource: !GetAtt CodeBuildProject.Arn
  #         - Effect: Allow
  #           Action:
  #             - codeconnections:UseConnection
  #             - codestar-connections:UseConnection
  #           Resource:
  #             - !Ref GithubConnectionArn

  # CodePipeline:
  #   Type: AWS::CodePipeline::Pipeline
  #   Properties:
  #     Name: !Sub "${AppName}-${Environment}-${BuildPurpose}-pipeline"
  #     RoleArn: !GetAtt CodePipelineRole.Arn

  #     ArtifactStore:
  #       Type: S3
  #       Location: !Ref LambdaBucket

  #     Stages:
  #       - Name: Source
  #         Actions:
  #           - Name: Source
  #             ActionTypeId:
  #               Category: Source
  #               Owner: AWS
  #               Provider: CodeStarSourceConnection
  #               Version: '1'
  #             Configuration:
  #               ConnectionArn: !Ref GithubConnectionArn
  #               FullRepositoryId: !Ref SourceRepo
  #               BranchName: !Ref SourceBranch
  #               DetectChanges: true
  #             OutputArtifacts:
  #               - Name: SourceArtifact

  #       - Name: Build
  #         Actions:
  #           - Name: Build
  #             ActionTypeId:
  #               Category: Build
  #               Owner: AWS
  #               Provider: CodeBuild
  #               Version: '1'
  #             Configuration:
  #               ProjectName: !Ref CodeBuildProject
  #             InputArtifacts:
  #               - Name: SourceArtifact