AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for Lambda Pipeline

Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger

  Environment:
    Type: String
    Description: Environment name

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN
    NoEcho: True

  SourceRepo:
    Type: String
    Description: owner/repo biçiminde GitHub repo ID'si

  SourceBranchPath:
    Type: String
    Description: logical purpose of produced artifact

  SourceBranch:
    Type: String

  BuildPurpose:
    Type: String
    Description: logical purpose of produced artifact

  LambdaBucket:
    Type: String
    Description: S3 bucket name used by lambda

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-${Environment}-${BuildPurpose}-build-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      Policies:
        - PolicyName: AdditionalPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${LambdaBucket}/*"

              - Sid: GitHubConnectionAccess
                Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                  - codestar-connections:GetConnectionToken
                  - codeconnections:UseConnection
                  - codeconnections:GetConnectionToken
                Resource: !Ref GithubConnectionArn

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AppName}-${Environment}-${BuildPurpose}-build-project"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Artifacts:
        Type: CODEPIPELINE 
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub "infrastructure/cicd/lambda/${BuildPurpose}/buildspec.yml"
      TimeoutInMinutes: 5

  ### IAM Role for CodePipeline
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-${Environment}-${BuildPurpose}-pipeline-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole

  CodePipelinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AppName}-${Environment}-${BuildPurpose}-pipeline-policy
      Roles:
        - !Ref CodePipelineRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowS3BucketAccess
            Effect: Allow
            Action:
              - s3:GetBucketVersioning
              - s3:GetBucketAcl
              - s3:GetBucketLocation
            Resource: !Sub "arn:aws:s3:::${LambdaBucket}/*"

          - Sid: AllowS3ObjectAccess
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: !Sub "arn:aws:s3:::${LambdaBucket}/*"

          - Effect: Allow
            Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
            Resource: !GetAtt CodeBuildProject.Arn
          - Effect: Allow
            Action:
              - codestar-connections:UseConnection
              - codestar-connections:GetConnectionToken
              - codeconnections:UseConnection
              - codeconnections:GetConnectionToken
            Resource:
              - !Ref GithubConnectionArn

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${AppName}-${Environment}-${BuildPurpose}-pipeline"
      RoleArn: !GetAtt CodePipelineRole.Arn

      ArtifactStore:
        Type: S3
        Location: !Ref LambdaBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref GithubConnectionArn
                FullRepositoryId: !Ref SourceRepo
                BranchName: !Ref SourceBranch
                DetectChanges: true
              OutputArtifacts:
                - Name: SourceArtifact

        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProject
                EnvironmentVariables: !Sub |
                  [
                    {
                      "name": "LambdaBucket",
                      "value": "${LambdaBucket}",
                      "type": "PLAINTEXT"
                    }
                  ]
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: OutputArtifact

      Triggers:
        - ProviderType: CodeStarSourceConnection
          GitConfiguration:
            SourceActionName: Source
            Push:
              - Branches:
                  Includes:
                    - !Sub ${SourceBranch}
                FilePaths:
                  Includes:
                    - !Sub "src/${SourceBranchPath}/**"