Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger

  Environment:
    Type: String
    Description: Environment name
    Default: dev

  LambdaBucket:
    Type: String
    Description: S3 bucket name used by lambda
    Default: ledger-app-aws-lambda

Resources:
  CfnExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-${Environment}-cfn-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaDeploymentPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:

              # # Lambda create/update
              # - Effect: Allow
              #   Action:
              #     - lambda:CreateFunction
              #     - lambda:UpdateFunctionCode
              #     - lambda:UpdateFunctionConfiguration
              #     - lambda:PublishVersion
              #     - lambda:DeleteFunction
              #     - lambda:GetFunction
              #     - lambda:TagResource
              #     - lambda:UntagResource
              #     - lambda:ListVersionsByFunction
              #   Resource: "*"

              # # Layer create/update
              # - Effect: Allow
              #   Action:
              #     - lambda:PublishLayerVersion
              #     - lambda:DeleteLayerVersion
              #     - lambda:GetLayerVersion
              #   Resource: "*"

              # IAM pass role (Lambda execution role için gerekli)
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  Fn::ImportValue: !Sub "${AppName}-${Environment}-lambda-function-execution-role-name"

              # CloudWatch Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource: 
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/lambda/layer*"

              # - Sid: AllowS3BucketAccess
              #   Effect: Allow
              #   Action:
              #     - s3:GetBucketVersioning
              #     - s3:GetBucketAcl
              #     - s3:GetBucketLocation
              #   Resource: !Sub "arn:aws:s3:::${LambdaBucket}/*"

              - Sid: AllowS3ObjectAccess
                Effect: Allow
                Action:
                  # - s3:PutObject
                  # - s3:PutObjectAcl
                  - s3:GetObject
                  # - s3:GetObjectVersion
                Resource: !Sub "arn:aws:s3:::${LambdaBucket}/*"

Outputs:
  CfnExecutionRoleName:
    Description: "Cfn Execution Role role Arn"
    Value: !GetAtt CfnExecutionRole.Arn
    Export:
      Name: !Sub "${AppName}-${Environment}-cfn-function-execution-role-name"