Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger
  Environment:
    Type: String
    Description: Environment name
    Default: dev

Resources:
  LambdaFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: DynamoDBAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: dynamodb:*
                  Resource: "*"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Environment}-lambda-function"
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaFunctionRole.Arn
      Timeout: 300
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "bootstrap"}

Outputs:
  LambdaFunctionName:
    Description: "Ledger lambda function name"
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub "${AppName}-${Environment}-lambda-function-name"
  LambdaFunctionArn:
    Description: "Ledger lambda function arn"
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub "${AppName}-${Environment}-lambda-function-arn"