Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger
  Environment:
    Type: String
    Description: Environment name
    Default: dev

  LambdaBucket:
    Type: String
    Description: S3 bucket name used by lambda
    Default: ledger-app-aws-lambda

  LambdaLayerKey:
    Type: String
    Description: S3 bucket key used by lambda layer zip
    Default: ledger_layer.zip

  LambdaFunctionKey:
    Type: String
    Description: S3 bucket key used by lambda function zip
    Default: ledger_function_noauth.zip

Resources:
  DatabaseInitFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: DynamoDBAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: dynamodb:*
                  Resource: "*"

  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub "${AppName}-${Environment}-lambda-layer"
      CompatibleRuntimes:
        - python3.12
      Content:
        S3Bucket: !Ref LambdaBucket
        S3Key: !Ref LambdaLayerKey

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Environment}-lambda-function"
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !GetAtt DatabaseInitFunctionRole.Arn
      Timeout: 300
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: !Ref LambdaFunctionKey
      Layers:
        - !Ref LambdaLayer

Outputs:
  LambdaFunctionName:
    Description: "Ledger lambda function name"
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub "${AppName}-${Environment}-lambda-function-name"
  LambdaFunctionArn:
    Description: "Ledger lambda function arn"
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub "${AppName}-${Environment}-lambda-function-arn"