version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: ledger-app-db:local
    container_name: ledger-db
    environment:
      MYSQL_ROOT_PASSWORD: devroot
      MYSQL_DATABASE: ledger
      MYSQL_USER: ledger
      MYSQL_PASSWORD: ledgerpass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data: