Parameters:
  AppName:
    Type: String

  Environment:
    Type: String

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${AppName}-${Environment}-${AWS::AccountId}-serverless-artifacts"
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  ArtifactBucketParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/artifact_bucket_s3"
      Type: String
      Value: !Sub "s3://${ArtifactBucket}"