Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN
    NoEcho: True

  SourceRepo:
    Type: String
    Description: owner/repo biçiminde GitHub repo ID'si

  SourceBranch:
    Type: String

Mappings:
  LambdaConfig:
    layer:
      BuildPurpose: layer
      SourceBranchPath: layers
    function:
      BuildPurpose: function
      SourceBranchPath: web

Resources:
  PipelineRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '{{resolve:ssm:/${AppName}/iac_bucket_url}}/app/pipeline/iam-role.yaml'
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        GithubConnectionArn: !Ref GithubConnectionArn

  LayerPipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - PipelineRoleStack
    Properties:
      TemplateURL: !Sub '{{resolve:ssm:/${AppName}/iac_bucket_url}}/app/pipeline/pipeline.yaml'
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        GithubConnectionArn: !Ref GithubConnectionArn
        SourceRepo: !Ref SourceRepo
        SourceBranch: !Ref SourceBranch
        SourceBranchPath: !FindInMap [LambdaConfig, layer, SourceBranchPath]
        BuildPurpose: !FindInMap [LambdaConfig, layer, BuildPurpose]

  FunctionPipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LayerPipelineStack
    Properties:
      TemplateURL: !Sub '{{resolve:ssm:/${AppName}/iac_bucket_url}}/app/pipeline/pipeline.yaml'
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        GithubConnectionArn: !Ref GithubConnectionArn
        SourceRepo: !Ref SourceRepo
        SourceBranch: !Ref SourceBranch
        SourceBranchPath: !FindInMap [LambdaConfig, function, SourceBranchPath]
        BuildPurpose: !FindInMap [LambdaConfig, function, BuildPurpose]