Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger
  Environment:
    Type: String
    Description: Environment name
    Default: dev

Resources:
  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${AppName}-${Environment}-api-gateway"
      ProtocolType: HTTP

  ApiGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGateway
      StageName: $default
      AutoDeploy: true

  CustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: ledger.zekibalci.com
      DomainNameConfigurations:
        - CertificateArn: arn:aws:acm:eu-north-1:253712034003:certificate/b50ea7e2-db47-4fab-b762-59c688a549d0
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2

  ApiGatewayMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref ApiGateway
      DomainName: !Ref CustomDomain
      Stage: $default

Outputs:
  ApiGatewayArn:
    Description: "Api Gateway Arn"
    Value: !Ref ApiGateway
    Export:
      Name: !Sub "${AppName}-${Environment}-api-gateway-arn"