version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  build:
    commands:
      - mkdir -p layer_build/python/lib/python3.12/site-packages
      - pip install -r src/layers/python/requirements.txt -t layer_build/python/lib/python3.12/site-packages

      - cd layer_build/

      - ZIP_NAME=layer-${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
      - zip -r ../../$ZIP_NAME python
      - pwd
      - ls -lha

      - aws s3 cp $ZIP_NAME s3://$LAMBDA_BUCKET/$ENVIRONMENT/layer/$ZIP_NAME