version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  build:
    commands:
      - |
        mkdir -p build/layer/python
        pip install -r src/layers/python/requirements.txt \
          -t build/layer/python

        cd build/layer
        zip -r ../../layer.zip .

artifacts:
  files:
    - 'layer.zip'