version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  build:
    commands:
      - |
        mkdir -p build/layer/python
        pip install -r src/layers/python/requirements.txt -t build/layer/python

        cd build/layer
        ZIP_NAME=function-${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
        zip -r ../$ZIP_NAME .

        aws s3 cp $ZIP_NAME s3://$LAMBDA_BUCKET/$ENVIRONMENT/layer/$ZIP_NAME
