version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  build:
    commands:

      # ---------- CHECK LAYER PIPELINE ----------
      - |
        LAYER_PIPELINE="${APP_NAME}-${ENVIRONMENT}-layer-pipeline"

        echo "Checking layer pipeline status: $LAYER_PIPELINE"

        while true; do
          RUNNING=$(aws codepipeline list-pipeline-executions \
            --pipeline-name "$LAYER_PIPELINE" \
            --query "pipelineExecutionSummaries[?status=='InProgress'] | length(@)" \
            --output text)

          if [ "$RUNNING" = "0" ]; then
            echo "Layer pipeline not running. Continue."
            break
          fi

          echo "Layer pipeline running... waiting 15s"
          sleep 15
        done

      # ---------- CREATE CODE ZIP FILE ----------
      - |
        cd src/web

        ZIP_NAME=function-${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
        S3_KEY="$ENVIRONMENT/function/$ZIP_NAME"

        zip -r $ZIP_NAME app config.py lambda_function.py
      
      # ---------- UPLOAD TO S3 ----------
      - |
        echo "Uploading artifact to S3..."
        aws s3 cp $ZIP_NAME s3://$LAMBDA_BUCKET/$S3_KEY

      # ---------- UPDATE FUNCTION CODE ----------
      - |
        FUNCTION_NAME="$APP_NAME-$ENVIRONMENT-lambda-function"

        echo "Updating Lambda function code..."
        aws lambda update-function-code \
          --function-name "$FUNCTION_NAME" \
          --s3-bucket "$LAMBDA_BUCKET" \
          --s3-key "$S3_KEY" \
          --publish