version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  build:
    commands:
      - cd src/web
      - ZIP_NAME=function-${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
      - zip -r $ZIP_NAME app config.py lambda_function.py
      - aws s3 cp $ZIP_NAME s3://$LambdaBucket/$ENVIRONMENT/$ZIP_NAME