Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger

  Environment:
    Type: String
    Description: Environment name
    Default: dev

  RootDomain:
    Type: String
    Description: Root Domain for Api Gateway
    Default: zbalci.com

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN
    Default: arn:aws:codeconnections:eu-north-1:253712034003:connection/2c02ecd9-b115-4cec-967f-a0e4445ecfaa
    NoEcho: True

  SourceRepo:
    Type: String
    Description: owner/repo biçiminde GitHub repo ID'si
    Default: zbalci/ledger-app-aws-serverless

  SourceBranch:
    Type: String
    Default: main
  
Resources:
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '{{resolve:ssm:/${AppName}/iac_bucket_url}}/app/cognito/user-pool.yaml'
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        RootDomain: !Ref RootDomain

  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '{{resolve:ssm:/${AppName}/iac_bucket_url}}/app/dynamodb/tables.yaml'
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '{{resolve:ssm:/${AppName}/iac_bucket_url}}/app/lambda/stack.yaml'
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        RootDomain: !Ref RootDomain

  GatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdaStack
    Properties:
      TemplateURL: !Sub '{{resolve:ssm:/${AppName}/iac_bucket_url}}/app/api_gateway/http-api.yaml'
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        RootDomain: !Ref RootDomain

  BuildStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdaStack
    Properties:
      TemplateURL: !Sub '{{resolve:ssm:/${AppName}/iac_bucket_url}}/app/build/stack.yaml'
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        GithubConnectionArn: !Ref GithubConnectionArn

  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - BuildStack
    Properties:
      TemplateURL: !Sub '{{resolve:ssm:/${AppName}/iac_bucket_url}}/app/pipeline/stack.yaml'
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        GithubConnectionArn: !Ref GithubConnectionArn
        SourceRepo: !Ref SourceRepo
        SourceBranch: !Ref SourceBranch