AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for Lambda Pipeline

Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger

  Environment:
    Type: String
    Description: Environment name

  BaseDomain:
    Type: String
    Description: Base Domain name

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN
    NoEcho: True

  SourceRepo:
    Type: String
    Description: owner/repo biçiminde GitHub repo ID'si

  SourceBranchPath:
    Type: String
    Description: logical purpose of produced artifact

  SourceBranch:
    Type: String

  BuildPurpose:
    Type: String
    Description: logical purpose of produced artifact

  LambdaBucket:
    Type: String
    Description: S3 bucket name used by lambda

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${AppName}-${Environment}-${BuildPurpose}-pipeline"
      RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${AppName}-${Environment}-lambda-pipeline-role"
      ArtifactStore:
        Type: S3
        Location: !Ref LambdaBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              Namespace: SourceVariables
              ActionTypeId: 
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref GithubConnectionArn
                FullRepositoryId: !Ref SourceRepo
                BranchName: !Ref SourceBranch
                DetectChanges: true
              OutputArtifacts:
                - Name: SourceArtifact

        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Sub "${AppName}-${Environment}-${BuildPurpose}-build-project"
                EnvironmentVariables: !Sub |
                  [
                    {
                      "name": "APP_NAME",
                      "value": "${AppName}",
                      "type": "PLAINTEXT"
                    },
                    {
                      "name": "ENVIRONMENT",
                      "value": "${Environment}",
                      "type": "PLAINTEXT"
                    },
                    {
                      "name": "LAMBDA_BUCKET",
                      "value": "${LambdaBucket}",
                      "type": "PLAINTEXT"
                    }
                  ]
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: OutputArtifact

        - Name: DeployLambda
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub "${AppName}-${Environment}-lambda-${BuildPurpose}-stack"
                TemplatePath: !Sub "SourceArtifact::infrastructure/cloudformation/lambda/${BuildPurpose}.yaml"
                RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${AppName}-${Environment}-cfn-execution-role"
                Capabilities: CAPABILITY_NAMED_IAM
                ParameterOverrides: !Sub |
                  {
                    "AppName": "${AppName}",
                    "Environment": "${Environment}",
                    "LambdaBucket": "${LambdaBucket}",
                    "LambdaArtifactKey": "${Environment}/${BuildPurpose}/${BuildPurpose}-#{SourceVariables.CommitId}.zip",
                    "BaseDomain": "${BaseDomain}"
                  }
              InputArtifacts:
                - Name: SourceArtifact

      Triggers:
        - ProviderType: CodeStarSourceConnection
          GitConfiguration:
            SourceActionName: Source
            Push:
              - Branches:
                  Includes:
                    - !Sub ${SourceBranch}
                FilePaths:
                  Includes:
                    - !Sub "src/${SourceBranchPath}/**"